name: Generate Novel Images
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # تم التحديث هنا

      - name: Set up Python
        uses: actions/setup-python@v5 # تم التحديث هنا
        with:
          python-version: '3.11' # استخدمنا نسخة أحدث من بايثون أيضاً

      - name: Install Requirements
        run: pip install requests firebase-admin 

      - name: Run Script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python generate_images.py
